version: '3.4'

services:
  db:
    image: mariadb:10.7
    container_name: streemi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streemi
      MYSQL_USER: Charles
      MYSQL_PASSWORD: Charles

  app:
    container_name: streemi-app
    build:
      context: ./
      dockerfile: docker/Dockerfile
      network: host
    volumes:
      - "./:/app"
    restart: always
    depends_on:
      - "db"
