services:
  app:
    container_name: streemi-app
    build:
      args:
        SYSTEM_PROCESSOR: x64
    environment:
      - APP_ENV=test
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    driver: bridge
